// Code generated by the Encore 1.48.13 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly communication: communication.ServiceClient
    public readonly course: course.ServiceClient
    public readonly library: library.ServiceClient
    public readonly user: user.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.communication = new communication.ServiceClient(base)
        this.course = new course.ServiceClient(base)
        this.library = new library.ServiceClient(base)
        this.user = new user.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createAnnouncement as api_communication_create_announcement_createAnnouncement } from "~backend/communication/create_announcement";
import { createWarning as api_communication_create_warning_createWarning } from "~backend/communication/create_warning";
import { listAnnouncements as api_communication_list_announcements_listAnnouncements } from "~backend/communication/list_announcements";
import { listMessages as api_communication_list_messages_listMessages } from "~backend/communication/list_messages";
import { listWarnings as api_communication_list_warnings_listWarnings } from "~backend/communication/list_warnings";
import { markRead as api_communication_mark_read_markRead } from "~backend/communication/mark_read";
import { sendMessage as api_communication_send_message_sendMessage } from "~backend/communication/send_message";

export namespace communication {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createAnnouncement = this.createAnnouncement.bind(this)
            this.createWarning = this.createWarning.bind(this)
            this.listAnnouncements = this.listAnnouncements.bind(this)
            this.listMessages = this.listMessages.bind(this)
            this.listWarnings = this.listWarnings.bind(this)
            this.markRead = this.markRead.bind(this)
            this.sendMessage = this.sendMessage.bind(this)
        }

        /**
         * Creates a new announcement.
         */
        public async createAnnouncement(params: RequestType<typeof api_communication_create_announcement_createAnnouncement>): Promise<ResponseType<typeof api_communication_create_announcement_createAnnouncement>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/communication/announcements`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_communication_create_announcement_createAnnouncement>
        }

        /**
         * Creates a warning for a student.
         */
        public async createWarning(params: RequestType<typeof api_communication_create_warning_createWarning>): Promise<ResponseType<typeof api_communication_create_warning_createWarning>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/communication/warnings`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_communication_create_warning_createWarning>
        }

        /**
         * Retrieves announcements, optionally filtered by audience, course, or active status.
         */
        public async listAnnouncements(params: RequestType<typeof api_communication_list_announcements_listAnnouncements>): Promise<ResponseType<typeof api_communication_list_announcements_listAnnouncements>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                courseId:       params.courseId === undefined ? undefined : String(params.courseId),
                isActive:       params.isActive === undefined ? undefined : String(params.isActive),
                targetAudience: params.targetAudience,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/communication/announcements`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_communication_list_announcements_listAnnouncements>
        }

        /**
         * Retrieves messages for a user, optionally filtered by type or read status.
         */
        public async listMessages(params: RequestType<typeof api_communication_list_messages_listMessages>): Promise<ResponseType<typeof api_communication_list_messages_listMessages>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                isRead: params.isRead === undefined ? undefined : String(params.isRead),
                type:   params.type,
                userId: String(params.userId),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/communication/messages`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_communication_list_messages_listMessages>
        }

        /**
         * Retrieves warnings, optionally filtered by student, course, type, or resolution status.
         */
        public async listWarnings(params: RequestType<typeof api_communication_list_warnings_listWarnings>): Promise<ResponseType<typeof api_communication_list_warnings_listWarnings>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                courseId:    params.courseId === undefined ? undefined : String(params.courseId),
                isResolved:  params.isResolved === undefined ? undefined : String(params.isResolved),
                studentId:   params.studentId === undefined ? undefined : String(params.studentId),
                warningType: params.warningType,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/communication/warnings`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_communication_list_warnings_listWarnings>
        }

        /**
         * Marks a message as read.
         */
        public async markRead(params: { messageId: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/communication/messages/${encodeURIComponent(params.messageId)}/read`, {method: "PUT", body: undefined})
        }

        /**
         * Sends a message from one user to another.
         */
        public async sendMessage(params: RequestType<typeof api_communication_send_message_sendMessage>): Promise<ResponseType<typeof api_communication_send_message_sendMessage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/communication/messages`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_communication_send_message_sendMessage>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_course_create_create } from "~backend/course/create";
import { enroll as api_course_enroll_enroll } from "~backend/course/enroll";
import { getAttendance as api_course_get_attendance_getAttendance } from "~backend/course/get_attendance";
import { getEnrollments as api_course_get_enrollments_getEnrollments } from "~backend/course/get_enrollments";
import { list as api_course_list_list } from "~backend/course/list";
import { markAttendance as api_course_mark_attendance_markAttendance } from "~backend/course/mark_attendance";
import { updateGrade as api_course_update_grade_updateGrade } from "~backend/course/update_grade";

export namespace course {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.enroll = this.enroll.bind(this)
            this.getAttendance = this.getAttendance.bind(this)
            this.getEnrollments = this.getEnrollments.bind(this)
            this.list = this.list.bind(this)
            this.markAttendance = this.markAttendance.bind(this)
            this.updateGrade = this.updateGrade.bind(this)
        }

        /**
         * Creates a new course.
         */
        public async create(params: RequestType<typeof api_course_create_create>): Promise<ResponseType<typeof api_course_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/courses`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_course_create_create>
        }

        /**
         * Enrolls a student in a course.
         */
        public async enroll(params: RequestType<typeof api_course_enroll_enroll>): Promise<ResponseType<typeof api_course_enroll_enroll>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/courses/enroll`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_course_enroll_enroll>
        }

        /**
         * Retrieves attendance records, optionally filtered by course, student, or date range.
         */
        public async getAttendance(params: RequestType<typeof api_course_get_attendance_getAttendance>): Promise<ResponseType<typeof api_course_get_attendance_getAttendance>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                courseId:  params.courseId === undefined ? undefined : String(params.courseId),
                endDate:   params.endDate === undefined ? undefined : params.endDate.toISOString(),
                startDate: params.startDate === undefined ? undefined : params.startDate.toISOString(),
                studentId: params.studentId === undefined ? undefined : String(params.studentId),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/courses/attendance`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_course_get_attendance_getAttendance>
        }

        /**
         * Retrieves enrollments, optionally filtered by course, student, or status.
         */
        public async getEnrollments(params: RequestType<typeof api_course_get_enrollments_getEnrollments>): Promise<ResponseType<typeof api_course_get_enrollments_getEnrollments>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                courseId:  params.courseId === undefined ? undefined : String(params.courseId),
                status:    params.status,
                studentId: params.studentId === undefined ? undefined : String(params.studentId),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/courses/enrollments`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_course_get_enrollments_getEnrollments>
        }

        /**
         * Retrieves all courses, optionally filtered by department, semester, year, or professor.
         */
        public async list(params: RequestType<typeof api_course_list_list>): Promise<ResponseType<typeof api_course_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                department:  params.department,
                professorId: params.professorId === undefined ? undefined : String(params.professorId),
                semester:    params.semester,
                year:        params.year === undefined ? undefined : String(params.year),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/courses`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_course_list_list>
        }

        /**
         * Marks attendance for a student in a course.
         */
        public async markAttendance(params: RequestType<typeof api_course_mark_attendance_markAttendance>): Promise<ResponseType<typeof api_course_mark_attendance_markAttendance>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/courses/attendance`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_course_mark_attendance_markAttendance>
        }

        /**
         * Updates a student's grade for a course.
         */
        public async updateGrade(params: RequestType<typeof api_course_update_grade_updateGrade>): Promise<ResponseType<typeof api_course_update_grade_updateGrade>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/courses/grade`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_course_update_grade_updateGrade>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { borrowBook as api_library_borrow_book_borrowBook } from "~backend/library/borrow_book";
import { createBook as api_library_create_book_createBook } from "~backend/library/create_book";
import { getStats as api_library_get_stats_getStats } from "~backend/library/get_stats";
import { listBooks as api_library_list_books_listBooks } from "~backend/library/list_books";
import { listBorrowings as api_library_list_borrowings_listBorrowings } from "~backend/library/list_borrowings";
import { returnBook as api_library_return_book_returnBook } from "~backend/library/return_book";

export namespace library {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.borrowBook = this.borrowBook.bind(this)
            this.createBook = this.createBook.bind(this)
            this.getStats = this.getStats.bind(this)
            this.listBooks = this.listBooks.bind(this)
            this.listBorrowings = this.listBorrowings.bind(this)
            this.returnBook = this.returnBook.bind(this)
        }

        /**
         * Allows a student to borrow a book from the library.
         */
        public async borrowBook(params: RequestType<typeof api_library_borrow_book_borrowBook>): Promise<ResponseType<typeof api_library_borrow_book_borrowBook>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/library/borrow`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_library_borrow_book_borrowBook>
        }

        /**
         * Creates a new book in the library.
         */
        public async createBook(params: RequestType<typeof api_library_create_book_createBook>): Promise<ResponseType<typeof api_library_create_book_createBook>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/library/books`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_library_create_book_createBook>
        }

        /**
         * Retrieves library statistics including total books, borrowings, and fines.
         */
        public async getStats(): Promise<ResponseType<typeof api_library_get_stats_getStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/library/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_library_get_stats_getStats>
        }

        /**
         * Retrieves all books, optionally filtered by category, author, or search term.
         */
        public async listBooks(params: RequestType<typeof api_library_list_books_listBooks>): Promise<ResponseType<typeof api_library_list_books_listBooks>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                author:   params.author,
                category: params.category,
                search:   params.search,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/library/books`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_library_list_books_listBooks>
        }

        /**
         * Retrieves borrowing records, optionally filtered by student, book, status, or overdue status.
         */
        public async listBorrowings(params: RequestType<typeof api_library_list_borrowings_listBorrowings>): Promise<ResponseType<typeof api_library_list_borrowings_listBorrowings>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                bookId:    params.bookId === undefined ? undefined : String(params.bookId),
                overdue:   params.overdue === undefined ? undefined : String(params.overdue),
                status:    params.status,
                studentId: params.studentId === undefined ? undefined : String(params.studentId),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/library/borrowings`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_library_list_borrowings_listBorrowings>
        }

        /**
         * Processes the return of a borrowed book and calculates any fines.
         */
        public async returnBook(params: RequestType<typeof api_library_return_book_returnBook>): Promise<ResponseType<typeof api_library_return_book_returnBook>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/library/return`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_library_return_book_returnBook>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_user_create_create } from "~backend/user/create";
import { deleteUser as api_user_delete_deleteUser } from "~backend/user/delete";
import { get as api_user_get_get } from "~backend/user/get";
import { list as api_user_list_list } from "~backend/user/list";
import { update as api_user_update_update } from "~backend/user/update";

export namespace user {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteUser = this.deleteUser.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new user in the system.
         */
        public async create(params: RequestType<typeof api_user_create_create>): Promise<ResponseType<typeof api_user_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_create_create>
        }

        /**
         * Deletes a user from the system.
         */
        public async deleteUser(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/users/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves a user by ID.
         */
        public async get(params: { id: number }): Promise<ResponseType<typeof api_user_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_get_get>
        }

        /**
         * Retrieves all users, optionally filtered by type or department.
         */
        public async list(params: RequestType<typeof api_user_list_list>): Promise<ResponseType<typeof api_user_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                department: params.department,
                userType:   params.userType === undefined ? undefined : String(params.userType),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_list_list>
        }

        /**
         * Updates an existing user.
         */
        public async update(params: RequestType<typeof api_user_update_update>): Promise<ResponseType<typeof api_user_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                address:    params.address,
                department: params.department,
                email:      params.email,
                name:       params.name,
                phone:      params.phone,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_update_update>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.48.13)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
